[build]
  publish = "dist/public"
  command = "npm ci --include=dev && npx vite build --config vite.config.prod.ts && npx tsx server/routes-serverless.ts --build-only && npx esbuild server/routes-serverless.ts --platform=node --packages=external --bundle --format=esm --outfile=dist/routes-serverless.mjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--include=dev"

[functions]
  included_files = ["dist/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200