[build]
  # No build command needed for static HTML files
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  # Apply these headers to all routes
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; font-src 'self'; img-src 'self' data:;"

[[headers]]
  # Cache static assets
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  # Cache CSS and JS longer
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Redirect rules
[[redirects]]
  from = "/presentation"
  to = "/deployment-success-presentation.html"
  status = 302

[[redirects]]
  from = "/research"
  to = "/research-enhanced-slide-deck.html"
  status = 302

[[redirects]]
  from = "/overview"
  to = "/slide-deck.html"
  status = 302

# Custom domain configuration
[[redirects]]
  from = "https://pnltoolkitpresentation.netlify.app/*"
  to = "https://pnltoolkitpresentation.professordtreku.com/:splat"
  status = 301
  force = true