import { Button } from "@/components/ui/button";
import { Download, Lightbulb } from "lucide-react";
import FacultyProfile from "@/components/faculty/profile-display";
import BackButton from "@/components/layout/back-button";

export default function Header() {
  const handleExportToolkit = () => {
    // Generate a comprehensive PBL toolkit document
    const currentDate = new Date().toLocaleDateString();
    const toolkitContent = `
# Pivot-and-Launch PBL Pedagogy Toolkit
**Generated on:** ${currentDate}

## Your Complete PBL Implementation Guide

### 1. Methodology Overview
The Pivot-and-Launch approach transforms traditional learning objectives into engaging, real-world project experiences.

### 2. Implementation Framework
- **Pivot Concepts**: Core knowledge anchors that provide foundational understanding
- **Launch Applications**: Real-world contexts where students apply their learning
- **Assessment Methods**: Authentic evaluation approaches aligned with project outcomes

### 3. Quick Start Guide
1. **Define Your Pivot**: Identify the essential knowledge students must acquire
2. **Design Your Launch**: Create authentic applications and contexts
3. **Plan Assessment**: Develop rubrics for both process and product evaluation
4. **Iterate and Improve**: Use student feedback to refine your approach

### 4. Supporting Tools Available
- ✅ Methodology Wizard - Step-by-step project setup
- ✅ Learning Objectives Converter - Transform traditional goals
- ✅ Student Collaboration Portal - Gather feedback and ideas
- ✅ Document Manager - Organize course materials
- ✅ Analytics Dashboard - Track engagement and progress

### 5. Professional Development Resources
Access ongoing support through:
- WPI Faculty Development Center
- PBL Community of Practice
- Online Training Modules
- Peer Mentoring Network

### 6. Technical Implementation Notes
- Platform URL: ${window.location.origin}
- User Guide: Available in Document Manager
- Support Contact: PBL-Support@wpi.edu

---
*This toolkit was generated by the WPI Pivot-and-Launch PBL Platform*
*For additional support, visit our help documentation or contact your instructional designer*
`;

    // Create and download the toolkit as a text file
    const blob = new Blob([toolkitContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `PBL-Toolkit-${currentDate.replace(/\//g, '-')}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
    
    console.log("PBL Toolkit exported successfully");
  };

  return (
    <header className="bg-white shadow-sm border-b border-gray-200 sticky top-0 z-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center h-16">
          <div className="flex items-center">
            <BackButton />
            <div className="flex-shrink-0 flex items-center">
              <div className="w-10 h-10 bg-red-600 rounded-lg flex items-center justify-center">
                <Lightbulb className="text-white w-5 h-5" />
              </div>
              <h1 className="ml-3 text-xl font-bold text-gray-800">
                Pivot-and-Launch PBL Pedagogy Tool
              </h1>
            </div>
          </div>
          
          <div className="flex items-center space-x-4">
            <Button 
              onClick={handleExportToolkit}
              className="bg-blue-800 text-white hover:bg-blue-700"
              data-testid="button-export-toolkit"
            >
              <Download className="w-4 h-4 mr-2" />
              Export Toolkit
            </Button>
            
            <FacultyProfile />
          </div>
        </div>
      </div>
    </header>
  );
}
